version: '2'
services:
  rabbit:
    image: rabbitmq:alpine
    environment:
      RABBITMQ_DEFAULT_USER: leaflow
      RABBITMQ_DEFAULT_PASS: leaflow
    networks:
      - data
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: leaflow
      POSTGRES_USER: leaflow
      POSTGRES_DB: leaflow
    networks:
      - backend
  leaftrigger:
    build:
      context: .
      dockerfile: dev.docker
    depends_on:
      - rabbit
      - db
    networks:
      - backend
      - data
networks:
  backend:
    driver: bridge
  data:
    driver: bridge
