version: '2'
networks:
  backend:
    driver: bridge
services:
  rabbitmq:
    image: rabbitmq
    networks:
      - backend
  trigger:
    build:
      context: .
      dockerfile: dev.docker
    environment:
      - RABBIT_MQ=ampq://rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - backend

